### ISSUE TITLE
Unexpected token?

### ISSUE THREAD

**Issue by openshiftninja** [cosmicjs/react-starter#1]
Following the instructions from the README, getting this error during **cosmic start**:

```
$ cosmic start
d82d8290-88a6-11e8-96d5-43db6338ad71
COSMIC_BUCKET=d82d8290-88a6-11e8-96d5-43db6338ad71 PORT=3000 npm start;
Starting app on port number 3000 connected to Bucket d82d8290-88a6-11e8-96d5-43db6338ad71.  Open your browser to http://localhost:3000

> react-starter@1.0.0 start /home/osninja/git/react-starter
> NODE_ENV=production node server.js


exec error: Error: Command failed: /bin/sh -c COSMIC_BUCKET=d82d8290-88a6-11e8-96d5-43db6338ad71 PORT=3000 npm start;
/home/osninja/git/react-starter/server.js:1
(function (exports, require, module, __filename, __dirname) { const { createServer } = require('http')

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-130-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-starter@1.0.0 start: `NODE_ENV=production node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-starter@1.0.0 start script 'NODE_ENV=production node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/osninja/git/react-starter/npm-debug.log
```

Commands issued:

```
npm i -g cosmic-cli
cosmic login
cosmic init react-starter
cd react-starter
cosmic start
```

I have little doubt that I can debug this, but it isn't quite working out of the box as specified in the README.

**Comment by openshiftninja** [comment]
Well that's embarrassing. The version of node I'm running is way out of date. Let me fix that. :)
